### ISSUE TITLE
Feature: 오늘의 Pick 랭킹

### ISSUE THREAD

**Issue by AhnJoonSung** [BoardPick/BoardPick-server#15]
## Feature Description
- 오늘 pick 많이 받은 10개 보드게임
- 보드게임id, 썸네일 이미지, 오늘의 Pick 랭킹, 보드게임 이름, 설명 반환

## To-Do
- [ ] user_board_game에서 Date가 오늘 날짜인거 가져오기
- [ ] 픽 수로 내림차순 정렬해서 상위 최대 10개에 대해 보드게임 id 가져오기
- [ ] 보드게임 id 기준으로 {보드게임id, 썸네일 이미지, 오늘의 Pick 랭킹, 보드게임 이름, 설명} 반환하기
