### ISSUE TITLE
Feature: 비슷한 보드게임

### ISSUE THREAD

**Issue by AhnJoonSung** [BoardPick/BoardPick-server#19]
## Feature Description
특정 보드게임과 비슷한 보드게임 리스트 제공 기능

반환 정보
- 보드게임 id
- 썸네일 이미지
- 원본 이미지
- 보드게임 이름
- pick 여부
- 설명
- 별점
- 보드게임 태그 

## To-Do
- [ ] 요청받은 보드게임id에 대해 카테고리 및 태그 가져오기
- [ ] 서비스 구현체에 따른 점수 부여 기준으로 상위 10개 선정
- [ ] 선정된 보드게임의 정보 반환
