### ISSUE TITLE
Feature: 추천 보드게임 추천 기준 변경

### ISSUE THREAD

**Issue by AhnJoonSung** [BoardPick/BoardPick-server#51]
## Feature Description
- 사용자의 pick 기반으로 가장 카테고리가 많이 매칭되는 게임 순으로 반환
- 사용자가 pick한게 없을 시 랜덤 10개 반환

## To-Do

- [ ] 유저가 pick한 보드게임들의 카테고리들을 누적합해서 순위 매김
- [ ] pick한게 없으면 랜덤 10개 반환
- [ ] 보드게임들을 순회 하며 카테고리 순서에 따른 점수순으로 정렬
